# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "pre-main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x,]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build --if-present
    - run: git config --global user.name "github-actions"
    - run: git config --global user.email "bastien.hoorelbeke@epita.fr"
    - run: git fetch
    - run: git checkout -b main
    - run: git pull 
    - run: cp -r dist/* .
    - run: git add .
    - run: git commit -m "UPDATE version from pre-main"
    - run: git push --set-upstream origin main
