name: Merge pre-main to main

on:
  push:
    branches: [ "pre-main" ]

jobs:
  merge-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour faire des merges

      - name: Install dependencies
        run: npm install

      - name: Build project (if applicable)
        run: npm run build --if-present

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "bh.69@live.fr"
          mkdir dist && git log -1 --pretty=%B > dist/last_commit_message.txt

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout main branch
        run: |
          git checkout main
      - name: Merge pre-main into main
        run: |
          git merge origin/pre-main --no-ff --commit -m "Auto-merge from pre-main to main" || git checkout pre-main -- .
      - name: Moving assets to main
        run: |
          rm -rf assets
          mv dist/* .
      - name: Add changes to git
        run: |
          git add .
      - name: Commit changes
        run: |
          git commit -F dist/last_commit_message.txt || echo "No changes to commit"

      - name: Push changes to main
        run: git push origin main
