name: Merge pre-main to main

on:
  push:
    branches: [ "pre-main" ]

jobs:
  merge-and-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important pour faire des merges

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build project (if applicable)
        run: npm run build --if-present

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "bh.69@live.fr"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout main branch
        run: |
          git checkout main
      - name: Merge pre-main into main
        run: |
          git checkout pre-main -- .  # Merge changes from pre-main to main
          git merge origin/pre-main --no-ff --commit -m "Auto-merge from pre-main to main"

      - name: Push changes to main
        run: git push origin main
